// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	entity "articles/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AuthorRepository is an autogenerated mock type for the AuthorRepository type
type AuthorRepository struct {
	mock.Mock
}

// GetAllByName provides a mock function with given fields: ctx, name
func (_m *AuthorRepository) GetAllByName(ctx context.Context, name string) (*[]entity.Author, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByName")
	}

	var r0 *[]entity.Author
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*[]entity.Author, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *[]entity.Author); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.Author)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIdAuthor provides a mock function with given fields: ctx, id
func (_m *AuthorRepository) GetByIdAuthor(ctx context.Context, id string) (*entity.Author, bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdAuthor")
	}

	var r0 *entity.Author
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Author, bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Author); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Author)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// InsertAuthor provides a mock function with given fields: ctx, req
func (_m *AuthorRepository) InsertAuthor(ctx context.Context, req *entity.Author) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertAuthor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Author) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthorRepository creates a new instance of AuthorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorRepository {
	mock := &AuthorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
