// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	dto "articles/shared/dto"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ArticlesService is an autogenerated mock type for the ArticlesService type
type ArticlesService struct {
	mock.Mock
}

// GetAllArticle provides a mock function with given fields: ctx, query
func (_m *ArticlesService) GetAllArticle(ctx context.Context, query *dto.QueryGetArticle) (*[]dto.ResponseGetArticles, int, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAllArticle")
	}

	var r0 *[]dto.ResponseGetArticles
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.QueryGetArticle) (*[]dto.ResponseGetArticles, int, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.QueryGetArticle) *[]dto.ResponseGetArticles); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]dto.ResponseGetArticles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.QueryGetArticle) int); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *dto.QueryGetArticle) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// InsertArticle provides a mock function with given fields: ctx, req
func (_m *ArticlesService) InsertArticle(ctx context.Context, req *dto.RequestArticle) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertArticle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RequestArticle) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewArticlesService creates a new instance of ArticlesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArticlesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArticlesService {
	mock := &ArticlesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
